name: testing
on:
  - push
  - pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm build

#      - name: Commit and push changes
#        uses: EndBug/add-and-commit@v9
#        with:
#          default_author: github_actions
#          add: |
#            - prices.json
#            - prices-regular.json
#            - prices-pve.json
#          message: 'Update prices'