const TermsAndConditionsStore = {
    Introduction: 'These Terms and Conditions ("Terms") govern your access to and use of our budgeting calculator service ("Koi Coin"). By accessing or using Koi Coin, you agree to be bound by these Terms. If you do not agree to these Terms, you must not access or use Koi Coin.',
    Terms: {
        "Registration and Account": 'To use Koi Coin, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for any activities or actions under your account, whether or not you have authorized such activities or actions.',
        "Subscription Plan and Fees": 'Koi Coin offers a monthly subscription plan. By subscribing to this plan, you will receive unlimited storage, additional pages, and other features. The subscription fees will be billed in advance on a monthly basis and are non-refundable. You may cancel your subscription at any time, but no refunds will be provided for any unused portion of the subscription period. We reserve the right to change the subscription fees at any time, and we will notify you of any changes.',
        "Data Collection and Privacy": 'We collect only the data that you enter into Koi Coin. Your data is stored securely in our database and will not be shared with third parties, except as required by law or as necessary to provide Koi Coin. We will handle your personal data in compliance with the General Data Protection Regulation (GDPR). Please review our Privacy Policy for more information on how we collect, use, and protect your personal data.',
        "Email Notifications": 'You can opt in or out of email notifications at any time by updating your account settings. By opting in, you agree to receive occasional emails regarding updates, promotions, and other information related to Koi Coin.',
        "Analytics and Anonymized Data": 'We may collect anonymous analytics data to help us understand user flow and user interactions with Koi Coin. This data is stored and processed in an anonymized form, ensuring that it cannot be used to personally identify you. The purpose of collecting this data is to improve the functionality and user experience of Koi Coin. If you prefer not to have your anonymized data collected, you can opt out by going to your account settings and turning off the analytics data collection option.',
        "Data Export and Account Deletion": 'You may download your data at any point during your use of Koi Coin. You may also delete your account at any time. Upon account deletion, all your data will be permanently deleted from our systems, and we will not be able to recover it.',
        "Limitation of Liability": 'To the maximum extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use Koi Coin.',
        "Changes to Terms and Conditions": 'We may modify these Terms at any time. If we make material changes to the Terms, we will notify you by email or through Koi Coin. By continuing to access or use Koi Coin after those changes become effective, you agree to be bound by the revised Terms.',
    },
    Conclusion: 'By using Koi Coin, you agree to be bound by the terms and conditions set forth in this document. If you have any questions or concerns, please contact Koi Coin\'s support team.'
};
export default TermsAndConditionsStore;